apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" .Release.Name }}
  labels:
    app: {{ printf "%s-backend" .Release.Name }}
spec:
  {{ if .Values.backend.replica.enabled | default false }}
  replicas: {{ .Values.backend.replica.count }}
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      app: {{ printf "%s-backend" .Release.Name }}
  template:
    metadata:
      name: {{ printf "%s-backend" .Release.Name }}
      labels:
        app: {{ printf "%s-backend" .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-backend" .Release.Name }}
          image: {{ required "Backend image name is required" .Values.backend.image.name }}:{{ required "Backend image tag is required" .Values.backend.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: BetterStack__Host
              value: {{ required "BetterStack Host is required" .Values.logging.betterstack.host }}
            - name: BetterStack__Token
              value: {{ required "BetterStack Token is required" .Values.logging.betterstack.token }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
      restartPolicy: Always
