apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-backend" .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  