{{ if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-issuer" .Release.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "Gateway TLS email is required" .Values.gateway.tls.email }}
    privateKeySecretRef:
      name: {{ printf "%s-issuer-private-key" .Release.Name }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ printf "%s-gateway" .Release.Name }}
                kind: Gateway
{{ end }}
