services:
  backend:
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: laurent-bot-backend:dev
    build:
      context: ..
      dockerfile: src/Backend/Dockerfile
    environment:
      Logging__MinimumLevels__Microsoft_AspNetCore: Warning
      Logging__MinimumLevels__Microsoft_EntityFrameworkCore: Information
      Logging__MinimumLevels__Microsoft_Extensions_Diagnostics: Information
      Database__backend__Host: postgres
      Database__backend__Port: 5432
      Database__backend__Database: laurentbot-backend
      Database__backend__User: laurentbot
      Database__backend__Password: laurentbot
    ports:
      - "8080:8080"
  bot:
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: laurent-bot-bot:dev
    build:
      context: ..
      dockerfile: src/Bot/Dockerfile
    environment:
      Logging__MinimumLevels__Microsoft_AspNetCore: Warning
      Logging__MinimumLevels__Microsoft_EntityFrameworkCore: Information
      Logging__MinimumLevels__Microsoft_Extensions_Diagnostics: Information
  frontend:
    image: laurent-bot-frontend:dev
    build:
      context: ../src/Frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
  rabbitmq:
    image: rabbitmq:4.2.4-alpine
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: laurentbot
      RABBITMQ_DEFAULT_PASS: laurentbot
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 1s
      timeout: 5s
      retries: 50
  postgres:
    image: postgres:18.3-alpine3.23
    environment:
      POSTGRES_USER: laurentbot
      POSTGRES_PASSWORD: laurentbot
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "laurentbot" ]
      interval: 1s
      timeout: 5s
      retries: 50

volumes:
  rabbitmq_data:
  postgres_data: