apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-bot" .Release.Name }}
  labels:
    app: {{ printf "%s-bot" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-bot" .Release.Name }}
  template:
    metadata:
      name: {{ printf "%s-bot" .Release.Name }}
      labels:
        app: {{ printf "%s-bot" .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-bot" .Release.Name }}
          image: {{ required "Bot image name is required" .Values.bot.image.name }}:{{ required "Bot image tag is required" .Values.bot.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: BetterStack__Host
              value: {{ required "BetterStack Host is required" .Values.logging.betterstack.host }}
            - name: BetterStack__Token
              value: {{ required "BetterStack Token is required" .Values.logging.betterstack.token }}
            {{ range .Values.logging.minimumLevels }}
            - name: Logging__MinimumLevels__{{ .name }}
              value: {{ .level }}
            {{ end }}
            {{ range $key, $value := .Values.database.profiles }}
            - name: Database__{{ $key }}__Host
              value: {{ required (printf "Database profile %s host is required" $key) $value.host | quote }}
            - name: Database__{{ $key }}__Port
              value: {{ required (printf "Database profile %s port is required" $key) $value.port | quote }}
            - name: Database__{{ $key }}__Database
              value: {{ required (printf "Database profile %s database is required" $key) $value.database | quote }}
            - name: Database__{{ $key }}__User
              value: {{ required (printf "Database profile %s user is required" $key) $value.user | quote }}
            - name: Database__{{ $key }}__Password
              value: {{ required (printf "Database profile %s password is required" $key) $value.password | quote }}
            {{ end }}
      restartPolicy: Always
