gateway:
  enabled: true
  className: cilium
  tls:
    email: ""
    enabled: false

rabbitmq:
  auth:
    user: ""
    password: ""

backend:
  replica:
    enabled: true
    count: 3
  image:
    name: "registry.digitalocean.com/saveapis/laurentbot-backend"
    tag: ""
  http:
    route:
      host: "api.laurentbot.saveapis.de"

bot:
  image:
    name: "registry.digitalocean.com/saveapis/laurentbot-bot"
    tag: ""

frontend:
  replica:
    enabled: true
    count: 3
  image:
    name: "registry.digitalocean.com/saveapis/laurentbot-frontend"
    tag: ""
  http:
    route:
      host: "laurentbot.saveapis.de"

logging:
  minimumLevels:
    - name: "Microsoft_AspNetCore"
      level: "Warning"
    - name: "Microsoft_Extensions_Diagnostics"
      level: "Information"
    - name: "Microsoft_EntityFrameworkCore"
      level: "Information"
  betterstack:
    host: ""
    token: ""

database:
  profiles:
    backend:
      host: ""
      port: 5432
      database: "laurentbot"
      user: ""
      password: ""