apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" .Release.Name }}
  labels:
    app: {{ printf "%s-frontend" .Release.Name }}
spec:
  {{ if required .Values.frontend.replica.enabled }}
  replicas: {{ .Values.frontend.replica.count }}
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      app: {{ printf "%s-frontend" .Release.Name }}
  template:
    metadata:
      name: {{ printf "%s-frontend" .Release.Name }}
      labels:
        app: {{ printf "%s-frontend" .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-frontend" .Release.Name }}
          image: {{ required "Frontend image name is required" .Values.frontend.image.name }}:{{ required "Frontend image tag is required" .Values.frontend.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
