apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-frontend-http-route" .Release.Name }}
spec:
  parentRefs:
    - name: {{ printf "%s-gateway" .Release.Name }}
  hostnames:
    - {{ .Values.frontend.http.route.host }}
  rules:
    - backendRefs:
        - name: {{ printf "%s-frontend" .Release.Name }}
          port: 8080