{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-frontend-http-route" .Release.Name }}
  labels:
    app: {{ printf "%s-frontend" .Release.Name }}
spec:
  parentRefs:
    - name: {{ printf "%s-gateway" .Release.Name }}
  hostnames:
    - {{ required "Frontend route hostname is required" .Values.frontend.http.route.host }}
  rules:
    - backendRefs:
        - name: {{ printf "%s-frontend" .Release.Name }}
          port: 8080
{{ end }}
