apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend" .Release.Name }}
  labels:
    app: {{ printf "%s-frontend" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-frontend" .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  