apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rabbitmq" .Release.Name }}
  labels:
    app: {{ printf "%s-rabbitmq" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-rabbitmq" .Release.Name }}
  template:
    metadata:
      name: {{ printf "%s-rabbitmq" .Release.Name }}
      labels:
        app: {{ printf "%s-rabbitmq" .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-rabbitmq" .Release.Name }}
          image: rabbitmq:4.2.4-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ required "RabbitMQ Username is required" .Values.rabbitmq.auth.user}}
            - name: RABBITMQ_DEFAULT_PASSWORD
              value: {{ required "RabbitMQ Password is required" .Values.rabbitmq.auth.password}}
          ports:
            - containerPort: 5672
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            exec:
              command: [ "rabbitmqctl", "status" ]
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      