apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rabbitmq" .Release.Name }}
  labels:
    app: {{ printf "%s-rabbitmq" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-rabbitmq" .Release.Name }}
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP
