name: CD
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/cd.yml
jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker Login
        uses: docker/login-action@v3.7.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_IMAGE_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: src/Backend/Dockerfile
          tags: registry.digitalocean.com/saveapis/laurentbot-backend:${{ github.sha }}
  deploy-bot:
    name: Deploy Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker Login
        uses: docker/login-action@v3.7.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_IMAGE_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: src/Bot/Dockerfile
          tags: registry.digitalocean.com/saveapis/laurentbot-bot:${{ github.sha }}
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker Login
        uses: docker/login-action@v3.7.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_IMAGE_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: src/Frontend
          tags: registry.digitalocean.com/saveapis/laurentbot-frontend:${{ github.sha }}